Repository jhnc-oss/yocto-image, pull requests merged in 2022-10, with the labels that each got.

#62 Update gitrepo to latest v2.16.7
  yocto-fc/Dockerfile
Labels: package: update

#64 Update gitrepo to 2.16.8
  yocto-fc/Dockerfile
Labels: package: update

#65 Add additional HOSTTOOLS needed by poky/kirkstone
  yocto-fc/Dockerfile
Labels: package: add

#66 Add Fedora 37 image build
  .github/workflows/ci.yml
  README.md
Labels: image: new
